# Name of your GitHub Actions workflow.
name: Publish to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: 0xc0170/jekyll-builder-for-github-pages-action@fix-safe-workspace
        with:
          secret_gh_pages_api_token: ${{ secrets.GH_PAGES_TOKEN }}
